### PR TITLE
Fix #[xdp("pktcapture")]

### PR DESCRIPTION
**Pull request by rhdxmr**
Hi @nitishm 

You asked a question thru [this issue](https://github.com/foniod/redbpf/issues/220#issuecomment-1003173600) in RedBPF. So I looked into your code and corrected some of your code.

First of all you should run the program as root since most of the BPF features require root privileges.

regards,

### CODE REVIEW

**Comment by nitishm** [comment]
Thanks a ton @rhdxmr. This really helps! I asked a few questions in the form of comments in the review 😊.

**Comment by rhdxmr** [comment]
You're welcome.
You mentioned that you asked a few questions in the review of this PR,
but I could not find any review or comment.
Did I misunderstand what you said?

**Comment by nitishm** [comment]
https://github.com/nitishm/xdp-flow-tuples/pull/1#discussion_r777041977

https://github.com/nitishm/xdp-flow-tuples/pull/1#discussion_r777042228

**Comment by rhdxmr** [comment]
I could not open the link you posted above. Even though I click the link, nothing happens.
But I could read a part of the question because preview is popped up while cursor is hovering.


> Should this always match the cargo crate name?
You can use whatever name you want. You can find the BPF program by name in the userspace program.
In your userspace program, the name is `pktcapture` so I named it.
```rust
    loaded
        .xdp_mut("pktcapture")
```

> Any reason you switched from eth0? The reason I ask is that, when I managed to run my code yester…

You can choose any interface name you want. I chose it since it is my wireless LAN card interface name.

**Comment by nitishm** [comment]
Got it. Thanks that answers the questions I had. 👍

**Pull request merged**
